<?php

use App\Enums\PartnerTypeEnum;
use App\Enums\PayableStatusEnum;
use App\Enums\RoleEnum;
use App\Models\Partner;
use App\Models\Payable;
use App\Models\Vendor;
use Carbon\Carbon;
use Inertia\Testing\AssertableInertia;

function getOrCreatePayableForTest(): Payable
{
    $existingPayable = Payable::query()->first();

    if ($existingPayable !== null) {
        return $existingPayable;
    }

    $supplier = Partner::query()
        ->where('type', PartnerTypeEnum::SUPPLIER->value)
        ->firstOrFail();
    $vendor = Vendor::query()->firstOrFail();

    return Payable::query()->create([
        'code' => 'PYB-TEST-'.str_pad((string) random_int(1, 999999), 6, '0', STR_PAD_LEFT),
        'description' => 'Payable created for feature test',
        'supplier_id' => $supplier->id,
        'vendor_id' => $vendor->id,
        'amount' => 1000.00,
        'issue_date' => Carbon::now()->format('Y-m-d'),
        'due_date' => Carbon::now()->addDays(15)->format('Y-m-d'),
        'status' => PayableStatusEnum::cases()[0]->value,
        'payment_method' => 'bank_transfer',
        'reference_number' => 'REF-TEST-001',
        'notes' => 'Generated by test helper',
        'user_id' => getSuperAdmin()->id,
    ]);
}

describe('tests for the "index" method of Management/PayableController', function () {
    $componentName = 'erp/payables/index';

    test('users without payable index permission get a 403 response', function () {
        $unauthorizedUser = getUserWithRole(RoleEnum::VENDOR->value);

        $this->actingAs($unauthorizedUser)
            ->get(route('erp.payables.index'))
            ->assertForbidden();
    });

    test('authorized users can access the payable listing', function () use ($componentName) {
        $authorizedUser = getSuperAdmin();

        $response = $this->actingAs($authorizedUser)->get(route('erp.payables.index'));

        $response->assertOk();
        $response->assertInertia(fn (AssertableInertia $page) => $page->component($componentName));
    });

    test('payable listing supports searching by code', function () {
        $authorizedUser = getSuperAdmin();
        $targetPayable = getOrCreatePayableForTest();

        $response = $this->actingAs($authorizedUser)->get(route('erp.payables.index', ['search' => $targetPayable->code]));

        $response->assertOk();
        $payables = $response->inertiaProps('payables.data');
        expect(collect($payables)->pluck('id'))->toContain($targetPayable->id);
    });

    test('payable listing supports sorting by id desc', function () {
        $authorizedUser = getSuperAdmin();
        getOrCreatePayableForTest();
        $expectedFirst = Payable::query()->orderBy('id', 'desc')->firstOrFail();

        $response = $this->actingAs($authorizedUser)->get(route('erp.payables.index', ['sort_by' => 'id', 'sort_dir' => 'desc']));

        $response->assertOk();
        $payables = $response->inertiaProps('payables.data');
        expect(collect($payables)->first()['id'])->toBe($expectedFirst->id);
    });

    test('payable listing supports pagination controls', function () {
        $authorizedUser = getSuperAdmin();

        $response = $this->actingAs($authorizedUser)->get(route('erp.payables.index', ['per_page' => 1]));

        $response->assertOk();
        $payables = $response->inertiaProps('payables.data');
        expect(count($payables))->toBeLessThanOrEqual(1);
    });

    test('payable listing supports status filtering', function () {
        $authorizedUser = getSuperAdmin();
        $targetPayable = getOrCreatePayableForTest();
        $status = $targetPayable->status?->value ?? $targetPayable->status;

        $response = $this->actingAs($authorizedUser)->get(route('erp.payables.index', [
            'filters' => ['status' => [$status]],
        ]));

        $response->assertOk();
        $payables = $response->inertiaProps('payables.data');
        expect(collect($payables)->pluck('id'))->toContain($targetPayable->id);
    });
});

describe('tests for the "create" method of Management/PayableController', function () {
    $componentName = 'erp/payables/create';

    test('users without payable create permission cannot access the create page', function () {
        $unauthorizedUser = getUserWithRole(RoleEnum::VENDOR->value);

        $this->actingAs($unauthorizedUser)
            ->get(route('erp.payables.create'))
            ->assertForbidden();
    });

    test('authorized users can access the payable creation page', function () use ($componentName) {
        $authorizedUser = getSuperAdmin();

        $response = $this->actingAs($authorizedUser)->get(route('erp.payables.create'));

        $response->assertOk();
        $response->assertInertia(fn (AssertableInertia $page) => $page->component($componentName));
    });
});

describe('tests for the "store" method of Management/PayableController', function () {
    test('users without payable create permission cannot store payables', function () {
        $unauthorizedUser = getUserWithRole(RoleEnum::VENDOR->value);

        $supplier = Partner::query()
            ->where('type', PartnerTypeEnum::SUPPLIER->value)
            ->firstOrFail();
        $vendor = Vendor::query()->firstOrFail();

        $payload = [
            'description' => 'Unauthorized payable attempt',
            'supplier_id' => $supplier->id,
            'vendor_id' => $vendor->id,
            'amount' => 1500.25,
            'due_date' => Carbon::now()->addDays(3)->format('Y-m-d'),
            'status' => PayableStatusEnum::cases()[0]->value,
            'payment_method' => 'bank_transfer',
            'reference_number' => 'REF-UNAUTH-001',
            'notes' => 'Unauthorized request',
        ];

        $this->actingAs($unauthorizedUser)
            ->post(route('erp.payables.store'), $payload)
            ->assertForbidden();
    });

    test('authorized users can store payables', function () {
        $authorizedUser = getSuperAdmin();

        $supplier = Partner::query()
            ->where('type', PartnerTypeEnum::SUPPLIER->value)
            ->firstOrFail();
        $vendor = Vendor::query()->firstOrFail();

        $payload = [
            'description' => 'Office internet service',
            'supplier_id' => $supplier->id,
            'vendor_id' => $vendor->id,
            'amount' => 2500.75,
            'due_date' => Carbon::now()->addDays(5)->format('Y-m-d'),
            'status' => PayableStatusEnum::cases()[0]->value,
            'payment_method' => 'bank_transfer',
            'reference_number' => 'REF-PAY-001',
            'notes' => 'Monthly internet invoice',
        ];

        $response = $this->actingAs($authorizedUser)->post(route('erp.payables.store'), $payload);

        $response->assertRedirect(route('erp.payables.index'));
        $this->assertDatabaseHas('payables', [
            'description' => $payload['description'],
            'supplier_id' => $payload['supplier_id'],
            'vendor_id' => $payload['vendor_id'],
            'amount' => $payload['amount'],
        ]);
    });
});

describe('tests for the "show" method of Management/PayableController', function () {
    $componentName = 'erp/payables/show';

    test('users without payable show permission cannot view payable details', function () {
        $unauthorizedUser = getUserWithRole(RoleEnum::VENDOR->value);
        $targetPayable = getOrCreatePayableForTest();

        $this->actingAs($unauthorizedUser)
            ->get(route('erp.payables.show', $targetPayable))
            ->assertForbidden();
    });

    test('authorized users can view payable details', function () use ($componentName) {
        $authorizedUser = getSuperAdmin();
        $targetPayable = getOrCreatePayableForTest();

        $this->withoutVite();

        $response = $this->actingAs($authorizedUser)
            ->get(route('erp.payables.show', $targetPayable));

        $response->assertOk();
        $response->assertInertia(fn (AssertableInertia $page) => $page
            ->component($componentName)
            ->has('payable')
            ->where('payable.id', $targetPayable->id)
        );
    });
});

describe('tests for the "edit" method of Management/PayableController', function () {
    $componentName = 'erp/payables/edit';

    test('users without payable edit permission cannot access edit page', function () {
        $unauthorizedUser = getUserWithRole(RoleEnum::VENDOR->value);
        $targetPayable = getOrCreatePayableForTest();

        $this->actingAs($unauthorizedUser)
            ->get(route('erp.payables.edit', $targetPayable))
            ->assertForbidden();
    });

    test('authorized users can access edit page', function () use ($componentName) {
        $authorizedUser = getSuperAdmin();
        $targetPayable = getOrCreatePayableForTest();

        $response = $this->actingAs($authorizedUser)->get(route('erp.payables.edit', $targetPayable));

        $response->assertOk();
        $response->assertInertia(fn (AssertableInertia $page) => $page->component($componentName));
        expect($response->inertiaProps('payable.id'))->toBe($targetPayable->id);
    });
});

describe('tests for the "update" method of Management/PayableController', function () {
    test('users without payable edit permission cannot update payables', function () {
        $unauthorizedUser = getUserWithRole(RoleEnum::VENDOR->value);
        $targetPayable = getOrCreatePayableForTest();

        $supplier = Partner::query()->where('type', PartnerTypeEnum::SUPPLIER->value)->firstOrFail();
        $vendor = Vendor::query()->firstOrFail();

        $payload = [
            'description' => 'Unauthorized update',
            'supplier_id' => $supplier->id,
            'vendor_id' => $vendor->id,
            'amount' => 1999.99,
            'due_date' => Carbon::now()->addDays(7)->format('Y-m-d'),
            'status' => PayableStatusEnum::cases()[0]->value,
            'payment_method' => 'cash',
            'reference_number' => 'REF-UPD-UNAUTH',
            'notes' => 'Unauthorized change',
        ];

        $this->actingAs($unauthorizedUser)
            ->put(route('erp.payables.update', $targetPayable), $payload)
            ->assertForbidden();
    });

    test('authorized users can update payables', function () {
        $authorizedUser = getSuperAdmin();
        $targetPayable = getOrCreatePayableForTest();

        $supplier = Partner::query()->where('type', PartnerTypeEnum::SUPPLIER->value)->firstOrFail();
        $vendor = Vendor::query()->firstOrFail();

        $payload = [
            'description' => 'Updated payable description',
            'supplier_id' => $supplier->id,
            'vendor_id' => $vendor->id,
            'amount' => 3210.5,
            'due_date' => Carbon::now()->addDays(10)->format('Y-m-d'),
            'status' => PayableStatusEnum::cases()[0]->value,
            'payment_method' => 'credit_card',
            'reference_number' => 'REF-UPD-001',
            'notes' => 'Updated notes',
        ];

        $response = $this->actingAs($authorizedUser)->put(route('erp.payables.update', $targetPayable), $payload);

        $response->assertRedirect(route('erp.payables.index'));
        $this->assertDatabaseHas('payables', [
            'id' => $targetPayable->id,
            'description' => $payload['description'],
            'supplier_id' => $payload['supplier_id'],
            'vendor_id' => $payload['vendor_id'],
            'amount' => $payload['amount'],
        ]);
    });
});
